// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp;

namespace TodoApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TodoApp.Models.Assignee", b =>
                {
                    b.Property<long>("AssigneeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("AssigneeId");

                    b.ToTable("Assignees");
                });

            modelBuilder.Entity("TodoApp.Models.Todo", b =>
                {
                    b.Property<long>("TodoId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AssigneeId");

                    b.Property<string>("Description");

                    b.Property<bool>("Done");

                    b.Property<string>("Title");

                    b.HasKey("TodoId");

                    b.HasIndex("AssigneeId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("TodoApp.Models.Todo", b =>
                {
                    b.HasOne("TodoApp.Models.Assignee")
                        .WithMany("TodoList")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
